name: Build World Server Dev Container

on:
  push:
    branches:
      - 'araxia-main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push worldserver Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/docker/Dockerfile
          target: build
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/araxiaonline/ac-wotlk-worldserver-devcontainer:latest

      - name: Image digest
        run: |
          echo "Image digest: ${{ steps.build-and-push.outputs.digest }}"
