name: araxia-docker-test
on:
  push:
    branches:
      - 'araxia-main'
# on:
#   release:
#     types: [published]

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
  cancel-in-progress: true

jobs:
  build-skeleton:
    #runs-on: "ubuntu-latest"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      # - name: Free up disk space
      #   run: |
      #     sudo rm -rf /usr/local/lib/android
      #     sudo rm -rf /usr/share/dotnet
      #     sudo rm -rf /opt/ghc
      #     sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Dockerhub Login
        run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Skeleton Container
        run: docker buildx build -t ghcr.io/araxiaonline/acore-skeleton:${{ github.event.release.tag_name }} --target skeleton --file ./apps/docker/Dockerfile .

      - name: Build Worldserver Container
        run: docker buildx build -t ghcr.io/araxiaonline/araxia-worldserver:${{ github.event.release.tag_name }} --target worldserver --file ./apps/docker/Dockerfile .

      - name: Build Authserver Container
        run: docker buildx build -t ghcr.io/araxiaonline/araxia-authserver:${{ github.event.release.tag_name }} --target authserver --file ./apps/docker/Dockerfile .

      - name: Build db-import Container
        run: docker buildx build -t ghcr.io/araxiaonline/araxia-authserver:${{ github.event.release.tag_name }} --target db-import --file ./apps/docker/Dockerfile .

      - name: Build client-data Container
        run: docker buildx build -t ghcr.io/araxiaonline/araxia-authserver:${{ github.event.release.tag_name }} --target client-data --file ./apps/docker/Dockerfile .

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push skeleton image
        run: docker push ghcr.io/araxiaonline/acore-skeleton:${{ github.event.release.tag_name }}

      - name: Push Worldserver image
        run: docker push ghcr.io/araxiaonline/araxia-worldserver:${{ github.event.release.tag_name }}

      - name: Push Authserver image
        run: docker push ghcr.io/araxiaonline/araxia-authserver:${{ github.event.release.tag_name }}

      - name: Push db-import image
        run: docker push ghcr.io/araxiaonline/araxia-authserver:${{ github.event.release.tag_name }}

      - name: Push client-data image
        run: docker push ghcr.io/araxiaonline/araxia-authserver:${{ github.event.release.tag_name }}

      # - name: build worldserver
      #   uses: ./.github/actions/docker-tag-and-build
      #   with:
      #     component-name: worldserver
      #     tags: ghcr.io/araxiaonline/azerothcore-worldserver:${{ github.event.release.tag_name }}
      #     push: true

