name: araxia-docker-test
on:
  push:
    branches:
      - 'araxia-main'

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
  cancel-in-progress: true

jobs:
  build-skeleton:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Build a Container
        run: docker build -t ghcr.io/araxiaonline/acore-skeleton:1 --target skeleton --file ./apps/docker/Dockerfile .
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push skeleton image
        run: docker push ghcr.io/araxiaonline/acore-skeleton:1
