name: Build World Server Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push worldserver Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/docker/Dockerfile
          target: worldserver
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/araxiaonline/ac-wotlk-worldserver:latest
            ghcr.io/araxiaonline/ac-wotlk-worldserver:${{ env.VERSION }}
          build-args: |
            USER_ID=${{ secrets.DOCKER_USER_ID }}
            GROUP_ID=${{ secrets.DOCKER_GROUP_ID }}
            DOCKER_USER=acore

      - name: Image digest
        run: |
          echo "Image digest: ${{ steps.build-and-push.outputs.digest }}"
